dist: trusty
sudo: required
language: go
go: '1.10'

install:
  - make setup
  - gem install fpm
  - npm install -g prettier
  - sudo apt-get update
  - sudo apt-get install --yes snapd rpm liblz4-dev
  - export PATH=/snap/bin:$PATH

script:
  - go build -o go-crawler-linux -i .

before_deploy:
   - git config --local user.name "bialas1993"
   - git config --local user.email "white@white.com"

deploy:
  - provider: releases
    api_key: "$GITHUB_TOKEN"
    file: "go-crawler-linux"
    skip_cleanup: true
  - provider: script
    skip_cleanup: true
    script: make ci
    on:
      tags: true

notifications:
  email: false

